/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
module

public import ZeroFree.Character
public import ZeroFree.Abacus.Transpose

/-!
# Reordering the parts

`chi` recurses on the *list* of parts, so `chi S w = chi S v` for `v` a permutation of `w` is a
theorem about that recursion rather than a triviality.

## Main definitions

* `ZeroFree.ChiSwapInvariant`: invariance of `chi` under transposing the first two parts.

## Main results

* `ZeroFree.chiSwapInvariant`: transposing the first two parts leaves `chi` unchanged.
* `ZeroFree.chi_perm`: `chi` does not see the order of the parts.

## Why the swap case is hard: it is not a bijection

`List.Perm` is generated by four constructors, and `chi` handles three of them for free:
`chi_perm_of_swap` discharges `nil`, `cons` and `trans`, reducing everything to the single
statement

```
chi S (b :: a :: l) = chi S (a :: b :: l)
```

Expanding both sides, each is a signed sum over two-step bead-move paths, writing the removal of a
`t`-hook at `x` as the bead move `x ↦ x - t`. The tempting proof pairs a path with the same two
moves performed in the other order. **That map is not defined**, and the obstruction is not an edge
case. Take

```
a = 1,  b = 2,  S = {2, 3}.
```

Forward (`b` then `a`), `3 ↦ 1` then `1 ↦ 0`, is valid: `1 ∉ S` and `0 ∉ S`. Reversed (`a` then
`b`) would need `3 ↦ 2` first, and `2 ∈ S`, so it is blocked; there is no `a`-then-`b` path with
those two moves at all. The forward path has no partner, and the identity survives only because the
forward terms cancel *among themselves*: the `b`-then-`a` order has exactly two paths to
`T = {0, 2}`,

| path | heights | sign |
| --- | --- | --- |
| `3 ↦ 1`, then `1 ↦ 0` | `ht₂(S,3) = |{2}| = 1`, `ht₁({1,2},1) = 0` | `-1` |
| `2 ↦ 0`, then `3 ↦ 2` | `ht₂(S,2) = 0`, `ht₁({0,3},3) = 0` | `+1` |

and their signs are opposite, so the coefficient of `chi T l` is `-1 + 1 = 0`. In the `a`-then-`b`
order the only `1`-hook is `2 ↦ 1`, after which no `2`-hook remains, so that coefficient is `0` as
well. The two sides agree by **cancellation across paths**, not by a term-by-term correspondence.
This is why the classical proof of Murnaghan–Nakayama order-independence runs through power sums,
where commutativity is free.

## The proof, in four cases

No sign-reversing involution is needed, because at most **two** two-step paths can land on a given
target bead set `T`, and `|T Δ S| ∈ {2, 4}`. The coefficient identity is therefore a finite case
analysis: fix `T`, enumerate the at most two paths on each side, and compare.

| `\|T Δ S\|` | paths | resolution |
| --- | --- | --- |
| 4 | 1 | generic; `swap_term_eq_of_generic`, paired by `(x,y) ↦ (y,x)` |
| 4 | 2 | two generic paths, each paired independently by the same swap |
| 2 | 1 | one path; the same path exists in the other order |
| 2 | 2 | `(p, p-b)` and `(p-a, p)`; they **cancel**, and the other order cancels or is empty |

A path is *generic* when it moves two distinct beads and neither move lands on the other's source.
The plain swap `(x, y) ↦ (y, x)` matches the generic paths of one order with those of the other,
preserving the target bead set (`rimHookRemoval_comm`) and the sign (`swap_sign_eq_of_generic`).

For a target with `|T Δ S| = 2`, write `T = S \ {p} ∪ {p - a - b}`, which determines `p`. The only
paths to `T` are

* `(x, y) = (p, p - b)` — the composite: bead `p` moves `b`, then the same bead moves `a`;
* `(x, y) = (p - a, p)` — the cascade: bead `p - a` moves `b`, then bead `p` moves `a` into the
  slot just vacated.

Their signs are opposite, because the bead at `p - a` lies inside the cascade's window and is
counted by neither of its two heights: this is `rimHookHeight_add_cascade` against
`rimHookHeight_add_composite`. So where both paths are present they cancel, which is the `(2,2)`
row — two forward terms summing to zero against a reverse sum that cancels or is empty.
-/

@[expose] public section

namespace ZeroFree

/-- Given reordering-invariance for one adjacent transposition at the head of the list, `chi` is
invariant under every permutation.

`List.Perm`'s other three constructors cost nothing: `nil` is reflexivity, `trans` is composition,
and `cons` is `Finset.sum_congr` against the recursion, because the induction hypothesis is
universally quantified over the bead set and the two sums are indexed by the *same* set of rim
hooks.

The hypothesis is stated for all `a`, `b`, `l` and `S` because the `cons` case applies it at a
*removal* of the ambient bead set, not at the set itself. -/
theorem chi_perm_of_swap
    (hswap : ∀ (a b : ℕ) (l : List ℕ) (S : BeadSet),
      chi S (b :: a :: l) = chi S (a :: b :: l))
    {w v : List ℕ} (h : w.Perm v) : ∀ S : BeadSet, chi S w = chi S v := by
  induction h with
  | nil => intro S; rfl
  | cons a h ih =>
      intro S
      rw [chi_cons, chi_cons]
      exact Finset.sum_congr rfl fun x _ => by rw [ih (rimHookRemoval a S x)]
  | swap a b l => intro S; exact hswap a b l S
  | trans h₁ h₂ ih₁ ih₂ => intro S; exact (ih₁ S).trans (ih₂ S)

/-- Invariance of `chi` under transposing the first two parts of the list — the swap case of
`List.Perm`, and the only one with content. See the module docstring for why it is not a bijection
argument. -/
def ChiSwapInvariant : Prop :=
  ∀ (a b : ℕ) (l : List ℕ) (S : BeadSet), chi S (b :: a :: l) = chi S (a :: b :: l)

/-- `chi` is invariant under permuting the parts, given `ChiSwapInvariant`. -/
theorem chi_perm_of_chiSwapInvariant (hs : ChiSwapInvariant)
    {w v : List ℕ} (h : w.Perm v) (S : BeadSet) : chi S w = chi S v :=
  chi_perm_of_swap hs h S


/-- **The two-step expansion of `chi`.** `chi S (b :: a :: l)` is a signed sum over *pairs* of bead
moves, with the two signs collected into one exponent and only `chi T l` left at the leaves. -/
theorem chi_cons_cons (S : BeadSet) (b a : ℕ) (l : List ℕ) :
    chi S (b :: a :: l)
      = ∑ x ∈ S.filter (fun x => b ≤ x ∧ x - b ∉ S),
          ∑ y ∈ (rimHookRemoval b S x).filter
              (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x),
            (-1 : ℤ) ^ (rimHookHeight b S x
                + rimHookHeight a (rimHookRemoval b S x) y)
              * chi (rimHookRemoval a (rimHookRemoval b S x) y) l := by
  rw [chi_cons]
  refine Finset.sum_congr rfl fun x _ => ?_
  rw [chi_cons, Finset.mul_sum]
  refine Finset.sum_congr rfl fun y _ => ?_
  rw [pow_add]
  ring


/-- **Non-interfering removals commute.** If the two bead moves `x ↦ x - b` and `y ↦ y - a` touch
different beads, and neither lands on the other's source, the two removals give the same bead set
in either order.

The three hypotheses are exactly the ways two moves can interfere:

* `x ≠ y` — the same bead moved twice;
* `y ≠ x - b` — the second move picks up the bead the first just placed;
* `x ≠ y - a` — the second move lands on the slot the first vacated.

Under all three, `insert` and `erase` interchange freely and both orders reduce to
`insert (y-a) (insert (x-b) ((S.erase x).erase y))`. -/
theorem rimHookRemoval_comm {a b : ℕ} {S : BeadSet} {x y : ℕ}
    (_hxy : x ≠ y) (hyb : y ≠ x - b) (hxa : x ≠ y - a) :
    rimHookRemoval a (rimHookRemoval b S x) y
      = rimHookRemoval b (rimHookRemoval a S y) x := by
  unfold rimHookRemoval
  ext z
  simp only [Finset.mem_insert, Finset.mem_erase]
  constructor
  · rintro (rfl | ⟨hzy, rfl | ⟨hzx, hzS⟩⟩)
    · exact Or.inr ⟨fun h => hxa h.symm, Or.inl rfl⟩
    · exact Or.inl rfl
    · exact Or.inr ⟨hzx, Or.inr ⟨hzy, hzS⟩⟩
  · rintro (rfl | ⟨hzx, rfl | ⟨hzy, hzS⟩⟩)
    · exact Or.inr ⟨fun h => hyb h.symm, Or.inl rfl⟩
    · exact Or.inl rfl
    · exact Or.inr ⟨hzy, Or.inr ⟨hzx, hzS⟩⟩


/-- **The height of a rim hook depends only on the beads in its open interval.** Two bead sets
agreeing on `Ioo (x - t) x` give the same height at `x`.

Since `rimHookRemoval` changes `S` at exactly two points, comparing heights before and after a
removal then only asks whether either point lies in the interval. The agreement hypothesis avoids
`ℕ` subtraction entirely, unlike the additive form `ht (removal) = ht S - [..] + [..]`, which
truncates. -/
theorem rimHookHeight_congr {t x : ℕ} {S T : BeadSet}
    (h : ∀ z ∈ Finset.Ioo (x - t) x, (z ∈ S ↔ z ∈ T)) :
    rimHookHeight t S x = rimHookHeight t T x := by
  rw [rimHookHeight_eq_filter_Ioo, rimHookHeight_eq_filter_Ioo]
  congr 1
  exact Finset.filter_congr fun z hz => by simpa using h z hz

/-- **A removal outside the interval leaves the height unchanged.** If neither the bead that moved
nor the slot it landed in lies strictly between `x - t` and `x`, the height at `x` is untouched. -/
theorem rimHookHeight_rimHookRemoval_of_notMem {t a x y : ℕ} {S : BeadSet}
    (hy : y ∉ Finset.Ioo (x - t) x) (hya : y - a ∉ Finset.Ioo (x - t) x) :
    rimHookHeight t (rimHookRemoval a S y) x = rimHookHeight t S x := by
  refine rimHookHeight_congr fun z hz => ?_
  have hzy : z ≠ y := fun h => hy (h ▸ hz)
  have hzya : z ≠ y - a := fun h => hya (h ▸ hz)
  unfold rimHookRemoval
  simp only [Finset.mem_insert, Finset.mem_erase]
  constructor
  · rintro (rfl | ⟨-, hzS⟩)
    · exact absurd rfl hzya
    · exact hzS
  · intro hzS
    exact Or.inr ⟨hzy, hzS⟩


/-- **The generic path pairs up completely: same set, same sign.**

Where two bead moves neither share a bead nor touch each other's endpoints, the term they
contribute to `chi S (b :: a :: l)` is *identical* to the term the reversed pair contributes to
`chi S (a :: b :: l)` — the removals agree by `rimHookRemoval_comm` and the signs agree by
`rimHookHeight_rimHookRemoval_of_notMem` applied on each side.

The hypotheses are the generic configuration: the three non-interference conditions of
`rimHookRemoval_comm`, plus, on each side, the two saying that the move's endpoints avoid the other
move's open interval, which is what the height lemma needs. -/
theorem swap_term_eq_of_generic {a b : ℕ} {S : BeadSet} {x y : ℕ} {l : List ℕ}
    (hxy : x ≠ y) (hyb : y ≠ x - b) (hxa : x ≠ y - a)
    (hy : y ∉ Finset.Ioo (x - b) x) (hya : y - a ∉ Finset.Ioo (x - b) x)
    (hx : x ∉ Finset.Ioo (y - a) y) (hxb : x - b ∉ Finset.Ioo (y - a) y) :
    (-1 : ℤ) ^ (rimHookHeight b S x
        + rimHookHeight a (rimHookRemoval b S x) y)
        * chi (rimHookRemoval a (rimHookRemoval b S x) y) l
      = (-1 : ℤ) ^ (rimHookHeight a S y
          + rimHookHeight b (rimHookRemoval a S y) x)
          * chi (rimHookRemoval b (rimHookRemoval a S y) x) l := by
  rw [rimHookRemoval_comm hxy hyb hxa]
  have h1 : rimHookHeight a (rimHookRemoval b S x) y = rimHookHeight a S y :=
    rimHookHeight_rimHookRemoval_of_notMem hx hxb
  have h2 : rimHookHeight b (rimHookRemoval a S y) x = rimHookHeight b S x :=
    rimHookHeight_rimHookRemoval_of_notMem hy hya
  rw [h1, h2, Nat.add_comm]


/-- **A `b`-hook forces `b ≥ 1`.** There are no `0`-hooks: `IsRimHook 0 S x` asks for `x ∈ S` and
`x - 0 ∉ S` at once. -/
theorem one_le_of_isRimHook {b : ℕ} {S : BeadSet} {x : ℕ} (h : IsRimHook b S x) :
    1 ≤ b := by
  obtain ⟨hxS, -, hxb⟩ := h
  rcases Nat.eq_zero_or_pos b with rfl | hb
  · exact absurd (by simpa using hxS) hxb
  · exact hb

/-- **The second move never touches the bead the first one moved.** The configuration `y = x` is
impossible, so the first of the three configurations left open by `rimHookRemoval_comm` is vacuous.

`rimHookRemoval b S x` *erases* `x` and puts a bead at `x - b`, and a `b`-hook forces `b ≥ 1`, so
`x - b < x`. Position `x` is therefore vacant afterwards, and `y` — which must be a bead of the new
set — cannot be `x`. -/
theorem ne_of_mem_rimHookRemoval {_a b : ℕ} {S : BeadSet} {x y : ℕ}
    (hx : IsRimHook b S x) (hy : y ∈ rimHookRemoval b S x) : y ≠ x := by
  have hb : 1 ≤ b := one_le_of_isRimHook hx
  have hxpos : 1 ≤ x := le_trans hb hx.2.1
  intro rfl
  unfold rimHookRemoval at hy
  simp only [Finset.mem_insert, Finset.mem_erase] at hy
  rcases hy with heq | ⟨hne, -⟩
  · omega
  · exact hne rfl


/-! ### The sign bookkeeping, as a count on one window

Every sign below is `(-1)` to the power of a bead count on an open interval, so all four cases of
the swap reduce to comparing two such counts. Two facts do all the work: a count splits at an
interior point, and a removal changes a count on a *fixed* window by at most the two positions it
touches. -/

/-- **Only the parity of an exponent survives.** -/
theorem neg_one_pow_eq_of_even_add {m n : ℕ} (h : (m + n) % 2 = 0) :
    (-1 : ℤ) ^ m = (-1 : ℤ) ^ n := by
  rcases Nat.even_or_odd m with hm | hm
  · have hn : Even n := by rw [Nat.even_iff] at hm ⊢; omega
    rw [hm.neg_one_pow, hn.neg_one_pow]
  · have hn : Odd n := by rw [Nat.odd_iff] at hm ⊢; omega
    rw [hm.neg_one_pow, hn.neg_one_pow]

/-- **A bead count splits at an interior point.** The count over `Ioo lo hi` is the two flanking
counts plus the bead at the splitting point itself, if any. -/
theorem card_filter_Ioo_split {S : BeadSet} {lo mid hi : ℕ} (h1 : lo < mid) (h2 : mid < hi) :
    ((Finset.Ioo lo hi).filter (fun z => z ∈ S)).card
      = ((Finset.Ioo lo mid).filter (fun z => z ∈ S)).card
        + ((Finset.Ioo mid hi).filter (fun z => z ∈ S)).card
        + (if mid ∈ S then 1 else 0) := by
  have hsplit : Finset.Ioo lo hi = Finset.Ioo lo mid ∪ insert mid (Finset.Ioo mid hi) := by
    ext z
    simp only [Finset.mem_Ioo, Finset.mem_union, Finset.mem_insert]
    omega
  have hdisj : Disjoint ((Finset.Ioo lo mid).filter (fun z => z ∈ S))
      ((insert mid (Finset.Ioo mid hi)).filter (fun z => z ∈ S)) := by
    rw [Finset.disjoint_left]
    intro z hz hz'
    simp only [Finset.mem_filter, Finset.mem_Ioo, Finset.mem_insert] at hz hz'
    obtain ⟨hz1, -⟩ := hz
    obtain ⟨hz2, -⟩ := hz'
    rcases hz2 with rfl | hz2 <;> omega
  have hnot : mid ∉ (Finset.Ioo mid hi).filter (fun z => z ∈ S) := by
    simp only [Finset.mem_filter, Finset.mem_Ioo, not_and]
    omega
  rw [hsplit, Finset.filter_union, Finset.card_union_of_disjoint hdisj, Finset.filter_insert]
  split_ifs with hmem
  · rw [Finset.card_insert_of_notMem hnot]
    omega
  · omega

/-- **A removal changes a bead count on a fixed window by its two endpoints only.** Removing the
`b`-hook at `x` takes the bead away from `x` and puts one at `x - b`, so on any window `K` the
count moves by whichever of those two positions lies in `K` — stated additively so no truncated
subtraction appears.

This is the quantitative form of `rimHookHeight_rimHookRemoval_of_notMem`: that lemma is the case
where neither endpoint is in the window. -/
theorem card_filter_rimHookRemoval_add {S : BeadSet} {b x : ℕ} (K : Finset ℕ)
    (hx : x ∈ S) (hxb : x - b ∉ S) (hne : x - b ≠ x) :
    (K.filter (fun z => z ∈ rimHookRemoval b S x)).card + (if x ∈ K then 1 else 0)
      = (K.filter (fun z => z ∈ S)).card + (if x - b ∈ K then 1 else 0) := by
  have hcard : ∀ c : ℕ, (K.filter (fun z => z = c)).card = if c ∈ K then 1 else 0 := by
    intro c
    rw [Finset.filter_eq']
    split_ifs <;> simp
  have key : K.filter (fun z => z ∈ rimHookRemoval b S x) ∪ K.filter (fun z => z = x)
      = K.filter (fun z => z ∈ S) ∪ K.filter (fun z => z = x - b) := by
    ext z
    simp only [Finset.mem_union, Finset.mem_filter, rimHookRemoval, Finset.mem_insert,
      Finset.mem_erase]
    constructor
    · rintro (⟨hzK, rfl | ⟨hzne, hzS⟩⟩ | ⟨hzK, rfl⟩)
      · exact Or.inr ⟨hzK, rfl⟩
      · exact Or.inl ⟨hzK, hzS⟩
      · exact Or.inl ⟨hzK, hx⟩
    · rintro (⟨hzK, hzS⟩ | ⟨hzK, rfl⟩)
      · by_cases hzx : z = x
        · exact Or.inr ⟨hzK, hzx⟩
        · exact Or.inl ⟨hzK, Or.inr ⟨hzx, hzS⟩⟩
      · exact Or.inl ⟨hzK, Or.inl rfl⟩
  have hd1 : Disjoint (K.filter (fun z => z ∈ rimHookRemoval b S x))
      (K.filter (fun z => z = x)) := by
    rw [Finset.disjoint_left]
    intro z hz hz'
    simp only [Finset.mem_filter, rimHookRemoval, Finset.mem_insert, Finset.mem_erase] at hz hz'
    obtain ⟨-, hz2⟩ := hz
    obtain ⟨-, rfl⟩ := hz'
    rcases hz2 with h | ⟨h, -⟩
    · exact hne h.symm
    · exact h rfl
  have hd2 : Disjoint (K.filter (fun z => z ∈ S)) (K.filter (fun z => z = x - b)) := by
    rw [Finset.disjoint_left]
    intro z hz hz'
    simp only [Finset.mem_filter] at hz hz'
    obtain ⟨-, hzS⟩ := hz
    obtain ⟨-, rfl⟩ := hz'
    exact hxb hzS
  have h := congrArg Finset.card key
  rw [Finset.card_union_of_disjoint hd1, Finset.card_union_of_disjoint hd2, hcard, hcard] at h
  exact h

/-- **The composite path's sign, as one count.** When the bead at `x` moves `b` and then the same
bead moves `a`, the two heights add up to the bead count on the whole window `Ioo (x - (a+b)) x` —
the intermediate position `x - b` contributes nothing precisely because it is empty. -/
theorem rimHookHeight_add_composite {a b : ℕ} {S : BeadSet} {x : ℕ}
    (ha : 1 ≤ a) (hb : 1 ≤ b) (hab : a + b ≤ x) (hx : x ∈ S) (hxb : x - b ∉ S) :
    rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) (x - b)
      = ((Finset.Ioo (x - (a + b)) x).filter (fun z => z ∈ S)).card := by
  have hsub : x - b - a = x - (a + b) := by omega
  simp only [rimHookHeight_eq_filter_Ioo, hsub]
  have hK := card_filter_rimHookRemoval_add (S := S) (b := b) (x := x)
    (Finset.Ioo (x - (a + b)) (x - b)) hx hxb (by omega)
  have hxK : x ∉ Finset.Ioo (x - (a + b)) (x - b) := by simp only [Finset.mem_Ioo]; omega
  have hxbK : x - b ∉ Finset.Ioo (x - (a + b)) (x - b) := by simp only [Finset.mem_Ioo]; omega
  rw [if_neg hxK, if_neg hxbK] at hK
  have hsp := card_filter_Ioo_split (S := S) (lo := x - (a + b)) (mid := x - b) (hi := x)
    (by omega) (by omega)
  rw [if_neg hxb] at hsp
  omega

/-- **The cascade path's sign, as one count, off by one.** When the bead at `x` moves `b` and then
the bead at `x + a` moves `a` into the slot just vacated, the two heights add up to the count on
`Ioo (x - b) (x + a)` *minus one*: the bead at `x` itself sits in the middle of that window and is
counted by neither height. It is that single missing bead which makes this path's sign opposite to
the composite one, and hence makes the two cancel. -/
theorem rimHookHeight_add_cascade {a b : ℕ} {S : BeadSet} {x : ℕ}
    (ha : 1 ≤ a) (hb : 1 ≤ b) (hbx : b ≤ x) (hx : x ∈ S) (hxb : x - b ∉ S) :
    rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) (x + a) + 1
      = ((Finset.Ioo (x + a - (a + b)) (x + a)).filter (fun z => z ∈ S)).card := by
  have h1 : x + a - a = x := by omega
  have h2 : x + a - (a + b) = x - b := by omega
  simp only [rimHookHeight_eq_filter_Ioo, h1, h2]
  have hK := card_filter_rimHookRemoval_add (S := S) (b := b) (x := x)
    (Finset.Ioo x (x + a)) hx hxb (by omega)
  have hxK : x ∉ Finset.Ioo x (x + a) := by simp only [Finset.mem_Ioo]; omega
  have hxbK : x - b ∉ Finset.Ioo x (x + a) := by simp only [Finset.mem_Ioo]; omega
  rw [if_neg hxK, if_neg hxbK] at hK
  have hsp := card_filter_Ioo_split (S := S) (lo := x - b) (mid := x) (hi := x + a)
    (by omega) (by omega)
  rw [if_pos hx] at hsp
  omega

/-- **The generic path's sign is order-independent.** This is the sign half of
`swap_term_eq_of_generic` with no interval hypotheses at all: the two exponents need not be equal,
but they always have the same parity.

The reason is a count of incidences. Each order's exponent differs from the other by whether the
moved bead, and the slot it lands in, fall inside the *other* move's window; and the four possible
incidences between two intervals with four distinct endpoints always number an even total — whether
the intervals are disjoint, nested or crossing — with `x - b ≠ y - a` exactly ruling out the odd
patterns. -/
theorem swap_sign_eq_of_generic {a b : ℕ} {S : BeadSet} {x y : ℕ}
    (ha : 1 ≤ a) (hb : 1 ≤ b) (hx : x ∈ S) (hbx : b ≤ x) (hxb : x - b ∉ S)
    (hy : y ∈ S) (hay : a ≤ y) (hya : y - a ∉ S)
    (hxy : x ≠ y) (hyxb : y ≠ x - b) (hxya : x ≠ y - a) (hd : x - b ≠ y - a) :
    (-1 : ℤ) ^ (rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) y)
      = (-1 : ℤ) ^ (rimHookHeight a S y + rimHookHeight b (rimHookRemoval a S y) x) := by
  apply neg_one_pow_eq_of_even_add
  simp only [rimHookHeight_eq_filter_Ioo]
  have h1 := card_filter_rimHookRemoval_add (S := S) (b := b) (x := x)
    (Finset.Ioo (y - a) y) hx hxb (by omega)
  have h2 := card_filter_rimHookRemoval_add (S := S) (b := a) (x := y)
    (Finset.Ioo (x - b) x) hy hya (by omega)
  have hpar : ((if x ∈ Finset.Ioo (y - a) y then 1 else 0)
      + (if x - b ∈ Finset.Ioo (y - a) y then 1 else 0)
      + (if y ∈ Finset.Ioo (x - b) x then 1 else 0)
      + (if y - a ∈ Finset.Ioo (x - b) x then 1 else 0)) % 2 = 0 := by
    simp only [Finset.mem_Ioo]
    split_ifs <;> omega
  omega


/-! ### The two degenerate paths and their common target

For a target differing from `S` in two positions, the module docstring names the only two paths
that can reach it: the *composite*, where the bead at `p` moves `b` and then moves `a` again, and
the *cascade*, where the bead at `p - a` moves `b` and then the bead at `p` moves `a` into the slot
just vacated. Both land on `insert (p - (a+b)) (S.erase p)`, and the two lemmas here say so. -/

/-- **The composite path's target.** Moving the bead at `x` by `b` and then by `a` deletes `x` and
installs a bead at `x - (a+b)`; the intermediate slot `x - b` is vacated again. -/
theorem rimHookRemoval_composite {a b : ℕ} {S : BeadSet} {x : ℕ} (hxb : x - b ∉ S) :
    rimHookRemoval a (rimHookRemoval b S x) (x - b) = insert (x - (a + b)) (S.erase x) := by
  have hsub : x - b - a = x - (a + b) := by omega
  have h1 : x - b ∉ S.erase x := fun h => hxb (Finset.mem_of_mem_erase h)
  unfold rimHookRemoval
  rw [Finset.erase_insert h1, hsub]

/-- **The cascade path's target.** Moving the bead at `x` by `b` and then the bead at `x + a` by
`a` puts a bead back at `x`, so the net effect is to delete `x + a` and install a bead at
`x - b = (x + a) - (a + b)` — the same shape of target as the composite path, with `p = x + a`. -/
theorem rimHookRemoval_cascade {a b : ℕ} {S : BeadSet} {x : ℕ}
    (ha : 1 ≤ a) (hbx : b ≤ x) (hx : x ∈ S) :
    rimHookRemoval a (rimHookRemoval b S x) (x + a)
      = insert (x + a - (a + b)) (S.erase (x + a)) := by
  have e1 : x + a - a = x := by omega
  have e2 : x + a - (a + b) = x - b := by omega
  have e3 : x - b ≠ x + a := by omega
  have e4 : x ≠ x + a := by omega
  have key : insert x ((S.erase x).erase (x + a)) = S.erase (x + a) := by
    ext z
    simp only [Finset.mem_insert, Finset.mem_erase]
    constructor
    · rintro (rfl | ⟨hza, hzx, hzS⟩)
      · exact ⟨e4, hx⟩
      · exact ⟨hza, hzS⟩
    · rintro ⟨hza, hzS⟩
      by_cases hzx : z = x
      · exact Or.inl hzx
      · exact Or.inr ⟨hza, hzx, hzS⟩
  unfold rimHookRemoval
  rw [e1, e2, Finset.erase_insert_of_ne e3, Finset.insert_comm, key]


/-- **The inner sum, split into its generic and degenerate parts.**

Fix the first move, a `b`-hook at `x`. The second move is at some `y` in the new bead set, and
there are exactly three possibilities: `y = x - b` (the composite), `y = x + a` (the cascade), or a
genuinely different bead, which is the generic case. So the inner sum of `chi_cons_cons` is the
generic part plus two isolated terms, and the two isolated terms have *opposite* signs — the
cascade's exponent is one less than the composite's, by `rimHookHeight_add_cascade`.

The generic part is stated over `S` rather than over the removal, which is what makes the whole
double sum symmetric in `a` and `b`: the conditions on `y` there mention only `S`, `x` and the two
hook lengths. -/
theorem chi_inner_split {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b) {S : BeadSet} {x : ℕ}
    (hx : x ∈ S) (hbx : b ≤ x) (hxb : x - b ∉ S) (l : List ℕ) :
    (∑ y ∈ (rimHookRemoval b S x).filter
          (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x),
        (-1 : ℤ) ^ (rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) y)
          * chi (rimHookRemoval a (rimHookRemoval b S x) y) l)
      = (∑ y ∈ S.filter (fun y => a ≤ y ∧ y - a ∉ S ∧ x ≠ y ∧ y ≠ x - b ∧ x ≠ y - a ∧
              x - b ≠ y - a),
          (-1 : ℤ) ^ (rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) y)
            * chi (rimHookRemoval a (rimHookRemoval b S x) y) l)
        + (if a ≤ x - b ∧ x - b - a ∉ S then
            (-1 : ℤ) ^ ((Finset.Ioo (x - (a + b)) x).filter (fun z => z ∈ S)).card
              * chi (insert (x - (a + b)) (S.erase x)) l else 0)
        - (if x + a ∈ S then
            (-1 : ℤ) ^ ((Finset.Ioo (x + a - (a + b)) (x + a)).filter (fun z => z ∈ S)).card
              * chi (insert (x + a - (a + b)) (S.erase (x + a))) l else 0) := by
  have hmemR : ∀ z : ℕ, z ∈ rimHookRemoval b S x ↔ (z = x - b ∨ (z ≠ x ∧ z ∈ S)) := by
    intro z
    simp only [rimHookRemoval, Finset.mem_insert, Finset.mem_erase]
  have hgen : ((rimHookRemoval b S x).filter
        (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x)).filter
          (fun y => ¬(y = x - b ∨ y = x + a))
      = S.filter (fun y => a ≤ y ∧ y - a ∉ S ∧ x ≠ y ∧ y ≠ x - b ∧ x ≠ y - a ∧
          x - b ≠ y - a) := by
    ext y
    simp only [Finset.mem_filter, hmemR]
    constructor
    · intro h
      obtain ⟨⟨hyR, hay, hyaR⟩, hdeg⟩ := h
      have hy1 : y ≠ x - b := fun hh => hdeg (Or.inl hh)
      have hy2 : y ≠ x + a := fun hh => hdeg (Or.inr hh)
      have hyS : y ∈ S := by
        rcases hyR with hh | ⟨-, hh⟩
        · exact absurd hh hy1
        · exact hh
      have hyx : y ≠ x := by
        rcases hyR with hh | ⟨hh, -⟩
        · exact absurd hh hy1
        · exact hh
      have hyax : y - a ≠ x := by omega
      have hyab : y - a ≠ x - b := fun hh => hyaR (Or.inl hh)
      exact ⟨hyS, hay, fun hh => hyaR (Or.inr ⟨hyax, hh⟩), Ne.symm hyx, hy1,
        Ne.symm hyax, Ne.symm hyab⟩
    · intro h
      obtain ⟨hyS, hay, hyaS, hxy, hyxb, hxya, hd⟩ := h
      refine ⟨⟨Or.inr ⟨Ne.symm hxy, hyS⟩, hay, ?_⟩, ?_⟩
      · intro hh
        rcases hh with hh | ⟨-, hh⟩
        · exact hd hh.symm
        · exact hyaS hh
      · intro hh
        rcases hh with hh | hh
        · exact hyxb hh
        · exact hxya (by omega)
  have hc1 : x - b ∈ (rimHookRemoval b S x).filter
        (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x)
      ↔ (a ≤ x - b ∧ x - b - a ∉ S) := by
    rw [Finset.mem_filter]
    constructor
    · rintro ⟨-, hax, hR⟩
      refine ⟨hax, fun hh => hR ?_⟩
      exact (hmemR _).mpr (Or.inr ⟨by omega, hh⟩)
    · rintro ⟨hax, hS⟩
      refine ⟨(hmemR _).mpr (Or.inl rfl), hax, fun hh => ?_⟩
      rcases (hmemR _).mp hh with hh1 | ⟨-, hh1⟩
      · omega
      · exact hS hh1
  have hc2 : x + a ∈ (rimHookRemoval b S x).filter
        (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x)
      ↔ x + a ∈ S := by
    rw [Finset.mem_filter]
    constructor
    · rintro ⟨hR, -, -⟩
      rcases (hmemR _).mp hR with hh | ⟨-, hh⟩
      · omega
      · exact hh
    · intro h
      refine ⟨(hmemR _).mpr (Or.inr ⟨by omega, h⟩), by omega, fun hh => ?_⟩
      rcases (hmemR _).mp hh with hh1 | ⟨hh1, -⟩
      · omega
      · exact hh1 (by omega)
  have hdisj : Disjoint
      (((rimHookRemoval b S x).filter
        (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x)).filter (fun y => y = x - b))
      (((rimHookRemoval b S x).filter
        (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x)).filter (fun y => y = x + a)) := by
    rw [Finset.disjoint_left]
    intro y hy hy'
    obtain ⟨-, h1⟩ := Finset.mem_filter.mp hy
    obtain ⟨-, h2⟩ := Finset.mem_filter.mp hy'
    omega
  have hsplit := Finset.sum_filter_add_sum_filter_not
      ((rimHookRemoval b S x).filter (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x))
      (fun y => y = x - b ∨ y = x + a)
      (fun y => (-1 : ℤ) ^ (rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) y)
        * chi (rimHookRemoval a (rimHookRemoval b S x) y) l)
  rw [← hsplit, hgen, Finset.filter_or, Finset.sum_union hdisj, Finset.filter_eq',
    Finset.filter_eq']
  have key1 : (∑ y ∈ (if x - b ∈ (rimHookRemoval b S x).filter
          (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x) then ({x - b} : Finset ℕ) else ∅),
        (-1 : ℤ) ^ (rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) y)
          * chi (rimHookRemoval a (rimHookRemoval b S x) y) l)
      = (if a ≤ x - b ∧ x - b - a ∉ S then
          (-1 : ℤ) ^ ((Finset.Ioo (x - (a + b)) x).filter (fun z => z ∈ S)).card
            * chi (insert (x - (a + b)) (S.erase x)) l else 0) := by
    by_cases h1 : a ≤ x - b ∧ x - b - a ∉ S
    · rw [if_pos (hc1.mpr h1), if_pos h1, Finset.sum_singleton,
        rimHookRemoval_composite hxb,
        rimHookHeight_add_composite ha hb (by omega) hx hxb]
    · rw [if_neg (fun hh => h1 (hc1.mp hh)), if_neg h1, Finset.sum_empty]
  have key2 : (∑ y ∈ (if x + a ∈ (rimHookRemoval b S x).filter
          (fun y => a ≤ y ∧ y - a ∉ rimHookRemoval b S x) then ({x + a} : Finset ℕ) else ∅),
        (-1 : ℤ) ^ (rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) y)
          * chi (rimHookRemoval a (rimHookRemoval b S x) y) l)
      = -(if x + a ∈ S then
          (-1 : ℤ) ^ ((Finset.Ioo (x + a - (a + b)) (x + a)).filter (fun z => z ∈ S)).card
            * chi (insert (x + a - (a + b)) (S.erase (x + a))) l else 0) := by
    by_cases h2 : x + a ∈ S
    · rw [if_pos (hc2.mpr h2), if_pos h2, Finset.sum_singleton,
        rimHookRemoval_cascade ha hbx hx, ← rimHookHeight_add_cascade ha hb hbx hx hxb,
        pow_succ]
      ring
    · rw [if_neg (fun hh => h2 (hc2.mp hh)), if_neg h2, Finset.sum_empty, neg_zero]
  rw [key1, key2]
  ring


/-- **`chi S (b :: a :: l)`, decomposed into a symmetric part and a generic part.** This is the
whole content of the swap case, and the point of it is what the three summands depend on.

The last two sums are indexed by the *target* `p`, and everything about them — the index set
`{p ∈ S : a + b ≤ p, p - (a+b) ∉ S}`, the sign, the bead set `insert (p - (a+b)) (S.erase p)` — is
symmetric in `a` and `b`. The two sums differ only in *which* of the two side conditions
`p - b ∉ S` and `p - a ∈ S` cuts them down, and since exactly one of `p - b ∉ S`, `p - b ∈ S` holds
(and likewise at `p - a`), interchanging `a` and `b` interchanges them up to the constant `∑` over
the whole index set. That is the cancellation the module docstring describes, in a form with no
case analysis left.

The first sum is generic: `y` ranges over beads of `S` itself, subject to conditions mentioning
only `S`, `x`, `a` and `b`, so the double sum is turned into the reversed one by the plain swap
`(x, y) ↦ (y, x)`, that is, by `Finset.sum_comm'`. -/
theorem chi_cons_cons_decomp {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b) (S : BeadSet) (l : List ℕ) :
    chi S (b :: a :: l)
      = (∑ x ∈ S.filter (fun x => b ≤ x ∧ x - b ∉ S),
          ∑ y ∈ S.filter (fun y => a ≤ y ∧ y - a ∉ S ∧ x ≠ y ∧ y ≠ x - b ∧ x ≠ y - a ∧
              x - b ≠ y - a),
            (-1 : ℤ) ^ (rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) y)
              * chi (rimHookRemoval a (rimHookRemoval b S x) y) l)
        + (∑ p ∈ (S.filter (fun p => a + b ≤ p ∧ p - (a + b) ∉ S)).filter (fun p => p - b ∉ S),
            (-1 : ℤ) ^ ((Finset.Ioo (p - (a + b)) p).filter (fun z => z ∈ S)).card
              * chi (insert (p - (a + b)) (S.erase p)) l)
        - (∑ p ∈ (S.filter (fun p => a + b ≤ p ∧ p - (a + b) ∉ S)).filter (fun p => p - a ∈ S),
            (-1 : ℤ) ^ ((Finset.Ioo (p - (a + b)) p).filter (fun z => z ∈ S)).card
              * chi (insert (p - (a + b)) (S.erase p)) l) := by
  -- The composite paths: the target `p` is the source of the first move.
  have hset1 : (S.filter (fun p => a + b ≤ p ∧ p - (a + b) ∉ S)).filter (fun p => p - b ∉ S)
      = (S.filter (fun x => b ≤ x ∧ x - b ∉ S)).filter
          (fun x => a ≤ x - b ∧ x - b - a ∉ S) := by
    ext p
    simp only [Finset.mem_filter]
    rw [show p - b - a = p - (a + b) from by omega]
    constructor
    · rintro ⟨⟨hpS, hab, hpab⟩, hpb⟩
      exact ⟨⟨hpS, by omega, hpb⟩, by omega, hpab⟩
    · rintro ⟨⟨hpS, hbp, hpb⟩, hap, hpab⟩
      exact ⟨⟨hpS, by omega, hpab⟩, hpb⟩
  have hD1 : (∑ p ∈ (S.filter (fun p => a + b ≤ p ∧ p - (a + b) ∉ S)).filter
        (fun p => p - b ∉ S),
        (-1 : ℤ) ^ ((Finset.Ioo (p - (a + b)) p).filter (fun z => z ∈ S)).card
          * chi (insert (p - (a + b)) (S.erase p)) l)
      = ∑ x ∈ S.filter (fun x => b ≤ x ∧ x - b ∉ S),
          (if a ≤ x - b ∧ x - b - a ∉ S then
            (-1 : ℤ) ^ ((Finset.Ioo (x - (a + b)) x).filter (fun z => z ∈ S)).card
              * chi (insert (x - (a + b)) (S.erase x)) l else 0) := by
    rw [← Finset.sum_filter]
    exact Finset.sum_congr hset1 fun _ _ => rfl
  -- The cascade paths: the target `p` is `a` above the source of the first move.
  have hD2 : (∑ p ∈ (S.filter (fun p => a + b ≤ p ∧ p - (a + b) ∉ S)).filter
        (fun p => p - a ∈ S),
        (-1 : ℤ) ^ ((Finset.Ioo (p - (a + b)) p).filter (fun z => z ∈ S)).card
          * chi (insert (p - (a + b)) (S.erase p)) l)
      = ∑ x ∈ S.filter (fun x => b ≤ x ∧ x - b ∉ S),
          (if x + a ∈ S then
            (-1 : ℤ) ^ ((Finset.Ioo (x + a - (a + b)) (x + a)).filter (fun z => z ∈ S)).card
              * chi (insert (x + a - (a + b)) (S.erase (x + a))) l else 0) := by
    rw [← Finset.sum_filter]
    refine Finset.sum_nbij' (fun p => p - a) (fun x => x + a) ?_ ?_ ?_ ?_ ?_
    · rintro p hp
      simp only [Finset.mem_filter] at hp ⊢
      obtain ⟨⟨hpS, hab, hpab⟩, hpa⟩ := hp
      refine ⟨⟨hpa, by omega, ?_⟩, ?_⟩
      · rwa [show p - a - b = p - (a + b) from by omega]
      · rwa [show p - a + a = p from by omega]
    · rintro x hx
      simp only [Finset.mem_filter] at hx ⊢
      obtain ⟨⟨hxS, hbx, hxb⟩, hxa⟩ := hx
      refine ⟨⟨hxa, by omega, ?_⟩, ?_⟩
      · rwa [show x + a - (a + b) = x - b from by omega]
      · rwa [show x + a - a = x from by omega]
    · rintro p hp
      simp only [Finset.mem_filter] at hp
      omega
    · rintro x hx
      omega
    · rintro p hp
      simp only [Finset.mem_filter] at hp
      rw [show p - a + a = p from by omega]
  rw [hD1, hD2, ← Finset.sum_add_distrib, ← Finset.sum_sub_distrib, chi_cons_cons]
  refine Finset.sum_congr rfl fun x hx => ?_
  obtain ⟨hxS, hbx, hxb⟩ := Finset.mem_filter.mp hx
  exact chi_inner_split ha hb hxS hbx hxb l


/-- **The generic double sum is order-independent.** The plain swap `(x, y) ↦ (y, x)` is a
bijection between the generic paths of the two orders — `Finset.sum_comm'`, whose hypothesis is
exactly the symmetry of the generic conditions — and it preserves each term, by
`rimHookRemoval_comm` on the bead set and `swap_sign_eq_of_generic` on the sign.

The right-hand side is literally the generic part of `chi_cons_cons_decomp` with `a` and `b`
interchanged, so this is the whole generic half of the swap case. -/
theorem chi_generic_sum_comm {a b : ℕ} (ha : 1 ≤ a) (hb : 1 ≤ b) (S : BeadSet) (l : List ℕ) :
    (∑ x ∈ S.filter (fun x => b ≤ x ∧ x - b ∉ S),
        ∑ y ∈ S.filter (fun y => a ≤ y ∧ y - a ∉ S ∧ x ≠ y ∧ y ≠ x - b ∧ x ≠ y - a ∧
            x - b ≠ y - a),
          (-1 : ℤ) ^ (rimHookHeight b S x + rimHookHeight a (rimHookRemoval b S x) y)
            * chi (rimHookRemoval a (rimHookRemoval b S x) y) l)
      = ∑ y ∈ S.filter (fun y => a ≤ y ∧ y - a ∉ S),
          ∑ x ∈ S.filter (fun x => b ≤ x ∧ x - b ∉ S ∧ y ≠ x ∧ x ≠ y - a ∧ y ≠ x - b ∧
              y - a ≠ x - b),
            (-1 : ℤ) ^ (rimHookHeight a S y + rimHookHeight b (rimHookRemoval a S y) x)
              * chi (rimHookRemoval b (rimHookRemoval a S y) x) l := by
  have hmem : ∀ x y : ℕ,
      (x ∈ S.filter (fun x => b ≤ x ∧ x - b ∉ S) ∧
        y ∈ S.filter (fun y => a ≤ y ∧ y - a ∉ S ∧ x ≠ y ∧ y ≠ x - b ∧ x ≠ y - a ∧
          x - b ≠ y - a))
      ↔ (x ∈ S.filter (fun x => b ≤ x ∧ x - b ∉ S ∧ y ≠ x ∧ x ≠ y - a ∧ y ≠ x - b ∧
            y - a ≠ x - b) ∧
        y ∈ S.filter (fun y => a ≤ y ∧ y - a ∉ S)) := by
    intro x y
    simp only [Finset.mem_filter]
    constructor
    · rintro ⟨⟨hxS, hbx, hxb⟩, hyS, hay, hya, hxy, hyxb, hxya, hd⟩
      exact ⟨⟨hxS, hbx, hxb, Ne.symm hxy, hxya, hyxb, Ne.symm hd⟩, hyS, hay, hya⟩
    · rintro ⟨⟨hxS, hbx, hxb, hyx, hxya, hyxb, hd⟩, hyS, hay, hya⟩
      exact ⟨⟨hxS, hbx, hxb⟩, hyS, hay, hya, Ne.symm hyx, hyxb, hxya, Ne.symm hd⟩
  rw [Finset.sum_comm' hmem]
  refine Finset.sum_congr rfl fun y hy => Finset.sum_congr rfl fun x hx => ?_
  obtain ⟨hyS, hay, hya⟩ := Finset.mem_filter.mp hy
  obtain ⟨hxS, hbx, hxb, hyx, hxya, hyxb, hd⟩ := Finset.mem_filter.mp hx
  rw [rimHookRemoval_comm (Ne.symm hyx) hyxb hxya,
    swap_sign_eq_of_generic ha hb hxS hbx hxb hyS hay hya (Ne.symm hyx) hyxb hxya (Ne.symm hd)]

/-- **There are no `0`-hooks, so a part `0` annihilates.** The index set of the recursion at
`t = 0` asks for a bead at `x` and no bead at `x - 0 = x`. -/
theorem chi_cons_zero (S : BeadSet) (l : List ℕ) : chi S (0 :: l) = 0 := by
  rw [chi_cons]
  refine Finset.sum_eq_zero fun x hx => ?_
  simp only [Finset.mem_filter, Nat.sub_zero] at hx
  exact absurd hx.1 hx.2.2

/-- **Transposing the first two parts leaves `chi` unchanged.**

Both orders are decomposed by `chi_cons_cons_decomp`. The generic parts agree by
`chi_generic_sum_comm`. The degenerate parts are two sums over the *same* symmetric index set
`C = {p ∈ S : a + b ≤ p, p - (a+b) ∉ S}`, cut down by `p - b ∉ S` and `p - a ∈ S` in one order and
by `p - a ∉ S` and `p - b ∈ S` in the other; since a filter and its negation split `C`, both
differences equal `∑_{p - b ∉ S} + ∑_{p - a ∉ S} - ∑_C`, which is symmetric in `a` and `b`.

That last step is the cancellation the module docstring describes: where a target is reached twice
in one order and not at all in the other, the two terms are the `p - b ∉ S` and `p - a ∈ S` rows at
the same `p`, and they cancel because `rimHookHeight_add_cascade` puts their exponents one
apart. -/
theorem chiSwapInvariant : ChiSwapInvariant := by
  intro a b l S
  rcases Nat.eq_zero_or_pos b with rfl | hb
  · rw [chi_cons_zero, chi_cons]
    exact (Finset.sum_eq_zero fun x _ => by rw [chi_cons_zero, mul_zero]).symm
  rcases Nat.eq_zero_or_pos a with rfl | ha
  · rw [chi_cons_zero, chi_cons]
    exact Finset.sum_eq_zero fun x _ => by rw [chi_cons_zero, mul_zero]
  rw [chi_cons_cons_decomp ha hb, chi_cons_cons_decomp hb ha, chi_generic_sum_comm ha hb,
    Nat.add_comm b a]
  have e1 := Finset.sum_filter_add_sum_filter_not
      (S.filter (fun p => a + b ≤ p ∧ p - (a + b) ∉ S)) (fun p => p - a ∉ S)
      (fun p => (-1 : ℤ) ^ ((Finset.Ioo (p - (a + b)) p).filter (fun z => z ∈ S)).card
        * chi (insert (p - (a + b)) (S.erase p)) l)
  have e2 := Finset.sum_filter_add_sum_filter_not
      (S.filter (fun p => a + b ≤ p ∧ p - (a + b) ∉ S)) (fun p => p - b ∉ S)
      (fun p => (-1 : ℤ) ^ ((Finset.Ioo (p - (a + b)) p).filter (fun z => z ∈ S)).card
        * chi (insert (p - (a + b)) (S.erase p)) l)
  rw [Finset.filter_congr (q := fun p => p - a ∈ S) fun p _ => not_not] at e1
  rw [Finset.filter_congr (q := fun p => p - b ∈ S) fun p _ => not_not] at e2
  omega

/-- **`chi` does not see the order of the parts.**

The three easy constructors of `List.Perm` are `chi_perm_of_swap`; the swap constructor is
`chiSwapInvariant`, which is where all the work is. -/
@[zf_tag "lem_chi_perm"]
theorem chi_perm {w v : List ℕ} (h : w.Perm v) (S : BeadSet) : chi S w = chi S v :=
  chi_perm_of_chiSwapInvariant chiSwapInvariant h S

end ZeroFree
